### ISSUE TITLE
Is there cpp examples for testing camera, Just like the python version of test_camera.py?

### ISSUE THREAD

**Issue by zener90818** [ifm/ifm3d-ros#38]
I‘m newcomer to ROS. Thanks a lot.

**Comment by theseankelly** [comment]
Hi @zener90818 -- there is no c++ example at the moment. However the ROS tutorials should get you pretty far along.

The core 'camera' node is what's called a nodelet, and you can read about how to use and start them here:
http://wiki.ros.org/nodelet/Tutorials

Otherwise, I recommend walking through the [introductory ROS tutorials](http://wiki.ros.org/ROS/Tutorials) on how to use topics/services -- once you understand these two things the ifm3d_ros package should look more familiar.

**Comment by theseankelly** [comment]
Feel free to reopen or create a new issue if other issues come up.
